param([switch]$Check)

$ErrorActionPreference = "Stop"
$protocolRoot = $PSScriptRoot
$repoRoot = Split-Path $protocolRoot -Parent
$schemaPath = Join-Path $protocolRoot "ring-abi.schema.json"
$schema = Get-Content -LiteralPath $schemaPath -Raw | ConvertFrom-Json

function Canonical-Fields($fields) {
    return ($fields | ForEach-Object { "$($_.name)@$($_.offset):$($_.type):$($_.size)" }) -join ";"
}

$canonical = "name=$($schema.name);version=$($schema.version);packing=$($schema.packing);headerSize=$($schema.headerSize);slotHeaderSize=$($schema.slotHeaderSize);slotCount=$($schema.slotCount);header=$(Canonical-Fields $schema.header);slot=$(Canonical-Fields $schema.slotHeader)"
$sha = [Security.Cryptography.SHA256]::Create()
try { $digest = $sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($canonical)) } finally { $sha.Dispose() }
$fingerprint = [BitConverter]::ToUInt64($digest, 0)
$fingerprintHex = "0x{0:x16}" -f $fingerprint
$shaHex = -join ($digest | ForEach-Object { $_.ToString("x2") })

$rustTypes = @{
    u16 = "u16"; u32 = "u32"; u64 = "u64";
    atomic_u32 = "std::sync::atomic::AtomicU32";
    atomic_i32 = "std::sync::atomic::AtomicI32";
    atomic_u64 = "std::sync::atomic::AtomicU64";
    bytes16 = "[u8; 16]"; bytes32 = "[u8; 32]"; u64x6 = "[u64; 6]"
}

function Rust-Assertions([string]$headerType, [string]$slotType) {
    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add("// Generated by protocol/generate-ring-abi.ps1. Do not edit.")
    $lines.Add("// Canonical source: protocol/ring-abi.schema.json")
    $lines.Add("pub const RING_ABI_HASH: u64 = $($fingerprintHex.Replace('0x','0x'));" )
    $lines.Add("pub const RING_ABI_LAYOUT_SHA256: &str = `"$shaHex`";")
    $lines.Add("pub const RING_HEADER_SIZE: usize = $($schema.headerSize);")
    $lines.Add("pub const SLOT_HEADER_SIZE: usize = $($schema.slotHeaderSize);")
    $lines.Add("pub const SLOT_COUNT: usize = $($schema.slotCount);")
    $lines.Add("const _: () = assert!(std::mem::size_of::<$headerType>() == RING_HEADER_SIZE);")
    $lines.Add("const _: () = assert!(std::mem::size_of::<$slotType>() == SLOT_HEADER_SIZE);")
    foreach ($field in $schema.header) {
        $type = $rustTypes[$field.type]
        $lines.Add("const _: fn(&$headerType) -> &$type = |value| &value.$($field.name);")
        $lines.Add("const _: () = assert!(std::mem::offset_of!($headerType, $($field.name)) == $($field.offset));")
        $lines.Add("const _: () = assert!(std::mem::size_of::<$type>() == $($field.size));")
    }
    foreach ($field in $schema.slotHeader) {
        $type = $rustTypes[$field.type]
        $lines.Add("const _: fn(&$slotType) -> &$type = |value| &value.$($field.name);")
        $lines.Add("const _: () = assert!(std::mem::offset_of!($slotType, $($field.name)) == $($field.offset));")
        $lines.Add("const _: () = assert!(std::mem::size_of::<$type>() == $($field.size));")
    }
    return ($lines -join "`n") + "`n"
}

$cpp = [Collections.Generic.List[string]]::new()
$cpp.Add("// Generated by protocol/generate-ring-abi.ps1. Do not edit.")
$cpp.Add("// Canonical source: protocol/ring-abi.schema.json")
$cpp.Add("#pragma once")
$cpp.Add("#define OCBR_ABI_HASH $($fingerprintHex)ULL")
$cpp.Add("#define OCBR_ABI_LAYOUT_SHA256 `"$shaHex`"")
$cpp.Add("static_assert(sizeof(OpenCamBridgeRingHeader) == $($schema.headerSize), `"ring header size changed`" );")
$cpp.Add("static_assert(sizeof(OpenCamBridgeSlotHeader) == $($schema.slotHeaderSize), `"slot header size changed`" );")
foreach ($field in $schema.header) {
    $cpp.Add("static_assert(offsetof(OpenCamBridgeRingHeader, $($field.cpp)) == $($field.offset), `"ring field offset changed: $($field.cpp)`" );")
    $cpp.Add("static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->$($field.cpp)) == $($field.size), `"ring field size changed: $($field.cpp)`" );")
}
foreach ($field in $schema.slotHeader) {
    $cpp.Add("static_assert(offsetof(OpenCamBridgeSlotHeader, $($field.cpp)) == $($field.offset), `"slot field offset changed: $($field.cpp)`" );")
    $cpp.Add("static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->$($field.cpp)) == $($field.size), `"slot field size changed: $($field.cpp)`" );")
}
$cppContent = ($cpp -join "`n") + "`n"

$outputs = @{
    (Join-Path $repoRoot "windows/virtual-camera-mediafoundation/VirtualCameraMediaSource/RingAbi.generated.h") = $cppContent
    (Join-Path $repoRoot "windows/virtual-camera-mediafoundation/rust-frame-producer/src/ring_abi_generated.rs") = (Rust-Assertions "OpenCamBridgeRingHeader" "OpenCamBridgeSlotHeader")
    (Join-Path $repoRoot "desktop/tauri-app/src-tauri/src/ring_abi_generated.rs") = (Rust-Assertions "RingHeader" "SlotHeader")
}

foreach ($entry in $outputs.GetEnumerator()) {
    if ($Check) {
        if (!(Test-Path -LiteralPath $entry.Key) -or (Get-Content -LiteralPath $entry.Key -Raw) -ne $entry.Value) {
            throw "Generated ring ABI file is stale: $($entry.Key). Run .\\protocol\\generate-ring-abi.ps1"
        }
    } else {
        [IO.File]::WriteAllText($entry.Key, $entry.Value, [Text.UTF8Encoding]::new($false))
        Write-Host "Generated $($entry.Key)"
    }
}

Write-Host "Ring ABI fingerprint $fingerprintHex (SHA-256 $shaHex)"
