// Generated by protocol/generate-ring-abi.ps1. Do not edit.
// Canonical source: protocol/ring-abi.schema.json
#pragma once
#define OCBR_ABI_HASH 0x9e97cb7c4b267ee7ULL
#define OCBR_ABI_LAYOUT_SHA256 "e77e264b7ccb979e6fd9b44705344d0418019c357335b38c335c68750484e574"
static_assert(sizeof(OpenCamBridgeRingHeader) == 320, "ring header size changed" );
static_assert(sizeof(OpenCamBridgeSlotHeader) == 128, "slot header size changed" );
static_assert(offsetof(OpenCamBridgeRingHeader, magic) == 0, "ring field offset changed: magic" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->magic) == 4, "ring field size changed: magic" );
static_assert(offsetof(OpenCamBridgeRingHeader, version) == 4, "ring field offset changed: version" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->version) == 2, "ring field size changed: version" );
static_assert(offsetof(OpenCamBridgeRingHeader, headerSize) == 6, "ring field offset changed: headerSize" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->headerSize) == 2, "ring field size changed: headerSize" );
static_assert(offsetof(OpenCamBridgeRingHeader, slotCount) == 8, "ring field offset changed: slotCount" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->slotCount) == 4, "ring field size changed: slotCount" );
static_assert(offsetof(OpenCamBridgeRingHeader, slotSize) == 12, "ring field offset changed: slotSize" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->slotSize) == 4, "ring field size changed: slotSize" );
static_assert(offsetof(OpenCamBridgeRingHeader, maxWidth) == 16, "ring field offset changed: maxWidth" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->maxWidth) == 4, "ring field size changed: maxWidth" );
static_assert(offsetof(OpenCamBridgeRingHeader, maxHeight) == 20, "ring field offset changed: maxHeight" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->maxHeight) == 4, "ring field size changed: maxHeight" );
static_assert(offsetof(OpenCamBridgeRingHeader, publishedSlot) == 24, "ring field offset changed: publishedSlot" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->publishedSlot) == 4, "ring field size changed: publishedSlot" );
static_assert(offsetof(OpenCamBridgeRingHeader, flags) == 28, "ring field offset changed: flags" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->flags) == 4, "ring field size changed: flags" );
static_assert(offsetof(OpenCamBridgeRingHeader, publishedSequence) == 32, "ring field offset changed: publishedSequence" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->publishedSequence) == 8, "ring field size changed: publishedSequence" );
static_assert(offsetof(OpenCamBridgeRingHeader, producerHeartbeatQpc) == 40, "ring field offset changed: producerHeartbeatQpc" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->producerHeartbeatQpc) == 8, "ring field size changed: producerHeartbeatQpc" );
static_assert(offsetof(OpenCamBridgeRingHeader, consumerWidth) == 48, "ring field offset changed: consumerWidth" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->consumerWidth) == 4, "ring field size changed: consumerWidth" );
static_assert(offsetof(OpenCamBridgeRingHeader, consumerHeight) == 52, "ring field offset changed: consumerHeight" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->consumerHeight) == 4, "ring field size changed: consumerHeight" );
static_assert(offsetof(OpenCamBridgeRingHeader, consumerFpsNum) == 56, "ring field offset changed: consumerFpsNum" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->consumerFpsNum) == 4, "ring field size changed: consumerFpsNum" );
static_assert(offsetof(OpenCamBridgeRingHeader, consumerFpsDen) == 60, "ring field offset changed: consumerFpsDen" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->consumerFpsDen) == 4, "ring field size changed: consumerFpsDen" );
static_assert(offsetof(OpenCamBridgeRingHeader, virtualCameraUniqueFrames) == 64, "ring field offset changed: virtualCameraUniqueFrames" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->virtualCameraUniqueFrames) == 8, "ring field size changed: virtualCameraUniqueFrames" );
static_assert(offsetof(OpenCamBridgeRingHeader, repeatedVirtualCameraSamples) == 72, "ring field offset changed: repeatedVirtualCameraSamples" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->repeatedVirtualCameraSamples) == 8, "ring field size changed: repeatedVirtualCameraSamples" );
static_assert(offsetof(OpenCamBridgeRingHeader, consumerAttached) == 80, "ring field offset changed: consumerAttached" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->consumerAttached) == 4, "ring field size changed: consumerAttached" );
static_assert(offsetof(OpenCamBridgeRingHeader, consumerPid) == 84, "ring field offset changed: consumerPid" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->consumerPid) == 4, "ring field size changed: consumerPid" );
static_assert(offsetof(OpenCamBridgeRingHeader, consumerHeartbeatQpc) == 88, "ring field offset changed: consumerHeartbeatQpc" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->consumerHeartbeatQpc) == 8, "ring field size changed: consumerHeartbeatQpc" );
static_assert(offsetof(OpenCamBridgeRingHeader, sampleRequests) == 96, "ring field offset changed: sampleRequests" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->sampleRequests) == 8, "ring field size changed: sampleRequests" );
static_assert(offsetof(OpenCamBridgeRingHeader, ringReadAttempts) == 104, "ring field offset changed: ringReadAttempts" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->ringReadAttempts) == 8, "ring field size changed: ringReadAttempts" );
static_assert(offsetof(OpenCamBridgeRingHeader, ringReadSuccesses) == 112, "ring field offset changed: ringReadSuccesses" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->ringReadSuccesses) == 8, "ring field size changed: ringReadSuccesses" );
static_assert(offsetof(OpenCamBridgeRingHeader, ringValidationFailures) == 120, "ring field offset changed: ringValidationFailures" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->ringValidationFailures) == 8, "ring field size changed: ringValidationFailures" );
static_assert(offsetof(OpenCamBridgeRingHeader, sampleCopyFailures) == 128, "ring field offset changed: sampleCopyFailures" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->sampleCopyFailures) == 8, "ring field size changed: sampleCopyFailures" );
static_assert(offsetof(OpenCamBridgeRingHeader, lastRingError) == 136, "ring field offset changed: lastRingError" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->lastRingError) == 4, "ring field size changed: lastRingError" );
static_assert(offsetof(OpenCamBridgeRingHeader, negotiatedSubtype) == 140, "ring field offset changed: negotiatedSubtype" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->negotiatedSubtype) == 4, "ring field size changed: negotiatedSubtype" );
static_assert(offsetof(OpenCamBridgeRingHeader, lastAcceptedSequence) == 144, "ring field offset changed: lastAcceptedSequence" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->lastAcceptedSequence) == 8, "ring field size changed: lastAcceptedSequence" );
static_assert(offsetof(OpenCamBridgeRingHeader, ringAbiHash) == 152, "ring field offset changed: ringAbiHash" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->ringAbiHash) == 8, "ring field size changed: ringAbiHash" );
static_assert(offsetof(OpenCamBridgeRingHeader, installedDllBuildHash) == 160, "ring field offset changed: installedDllBuildHash" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->installedDllBuildHash) == 32, "ring field size changed: installedDllBuildHash" );
static_assert(offsetof(OpenCamBridgeRingHeader, producerBuildHash) == 192, "ring field offset changed: producerBuildHash" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->producerBuildHash) == 32, "ring field size changed: producerBuildHash" );
static_assert(offsetof(OpenCamBridgeRingHeader, producerFpsNum) == 224, "ring field offset changed: producerFpsNum" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->producerFpsNum) == 4, "ring field size changed: producerFpsNum" );
static_assert(offsetof(OpenCamBridgeRingHeader, producerFpsDen) == 228, "ring field offset changed: producerFpsDen" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->producerFpsDen) == 4, "ring field size changed: producerFpsDen" );
static_assert(offsetof(OpenCamBridgeRingHeader, resizeBackend) == 232, "ring field offset changed: resizeBackend" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->resizeBackend) == 4, "ring field size changed: resizeBackend" );
static_assert(offsetof(OpenCamBridgeRingHeader, resizeFailures) == 236, "ring field offset changed: resizeFailures" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->resizeFailures) == 4, "ring field size changed: resizeFailures" );
static_assert(offsetof(OpenCamBridgeRingHeader, ringWriteSequence) == 240, "ring field offset changed: ringWriteSequence" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->ringWriteSequence) == 8, "ring field size changed: ringWriteSequence" );
static_assert(offsetof(OpenCamBridgeRingHeader, streamGeneration) == 248, "ring field offset changed: streamGeneration" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->streamGeneration) == 8, "ring field size changed: streamGeneration" );
static_assert(offsetof(OpenCamBridgeRingHeader, ringFramesOverwritten) == 256, "ring field offset changed: ringFramesOverwritten" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->ringFramesOverwritten) == 8, "ring field size changed: ringFramesOverwritten" );
static_assert(offsetof(OpenCamBridgeRingHeader, playoutBufferDepthNs) == 264, "ring field offset changed: playoutBufferDepthNs" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->playoutBufferDepthNs) == 8, "ring field size changed: playoutBufferDepthNs" );
static_assert(offsetof(OpenCamBridgeRingHeader, playoutTargetDelayNs) == 272, "ring field offset changed: playoutTargetDelayNs" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->playoutTargetDelayNs) == 8, "ring field size changed: playoutTargetDelayNs" );
static_assert(offsetof(OpenCamBridgeRingHeader, playoutLateDropped) == 280, "ring field offset changed: playoutLateDropped" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->playoutLateDropped) == 8, "ring field size changed: playoutLateDropped" );
static_assert(offsetof(OpenCamBridgeRingHeader, playoutUnderruns) == 288, "ring field offset changed: playoutUnderruns" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->playoutUnderruns) == 8, "ring field size changed: playoutUnderruns" );
static_assert(offsetof(OpenCamBridgeRingHeader, playoutSchedulerResets) == 296, "ring field offset changed: playoutSchedulerResets" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->playoutSchedulerResets) == 8, "ring field size changed: playoutSchedulerResets" );
static_assert(offsetof(OpenCamBridgeRingHeader, playoutClockPpm) == 304, "ring field offset changed: playoutClockPpm" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->playoutClockPpm) == 4, "ring field size changed: playoutClockPpm" );
static_assert(offsetof(OpenCamBridgeRingHeader, playoutMaxOutputGapMs) == 308, "ring field offset changed: playoutMaxOutputGapMs" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->playoutMaxOutputGapMs) == 4, "ring field size changed: playoutMaxOutputGapMs" );
static_assert(offsetof(OpenCamBridgeRingHeader, reserved) == 312, "ring field offset changed: reserved" );
static_assert(sizeof(((OpenCamBridgeRingHeader*)0)->reserved) == 8, "ring field size changed: reserved" );
static_assert(offsetof(OpenCamBridgeSlotHeader, writeEpoch) == 0, "slot field offset changed: writeEpoch" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->writeEpoch) == 8, "slot field size changed: writeEpoch" );
static_assert(offsetof(OpenCamBridgeSlotHeader, sequence) == 8, "slot field offset changed: sequence" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->sequence) == 8, "slot field size changed: sequence" );
static_assert(offsetof(OpenCamBridgeSlotHeader, captureTimestampNs) == 16, "slot field offset changed: captureTimestampNs" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->captureTimestampNs) == 8, "slot field size changed: captureTimestampNs" );
static_assert(offsetof(OpenCamBridgeSlotHeader, receiveTimestampNs) == 24, "slot field offset changed: receiveTimestampNs" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->receiveTimestampNs) == 8, "slot field size changed: receiveTimestampNs" );
static_assert(offsetof(OpenCamBridgeSlotHeader, decodeTimestampNs) == 32, "slot field offset changed: decodeTimestampNs" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->decodeTimestampNs) == 8, "slot field size changed: decodeTimestampNs" );
static_assert(offsetof(OpenCamBridgeSlotHeader, width) == 40, "slot field offset changed: width" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->width) == 4, "slot field size changed: width" );
static_assert(offsetof(OpenCamBridgeSlotHeader, height) == 44, "slot field offset changed: height" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->height) == 4, "slot field size changed: height" );
static_assert(offsetof(OpenCamBridgeSlotHeader, yStride) == 48, "slot field offset changed: yStride" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->yStride) == 4, "slot field size changed: yStride" );
static_assert(offsetof(OpenCamBridgeSlotHeader, uvStride) == 52, "slot field offset changed: uvStride" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->uvStride) == 4, "slot field size changed: uvStride" );
static_assert(offsetof(OpenCamBridgeSlotHeader, pixelFormat) == 56, "slot field offset changed: pixelFormat" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->pixelFormat) == 4, "slot field size changed: pixelFormat" );
static_assert(offsetof(OpenCamBridgeSlotHeader, payloadSize) == 60, "slot field offset changed: payloadSize" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->payloadSize) == 4, "slot field size changed: payloadSize" );
static_assert(offsetof(OpenCamBridgeSlotHeader, flags) == 64, "slot field offset changed: flags" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->flags) == 4, "slot field size changed: flags" );
static_assert(offsetof(OpenCamBridgeSlotHeader, dataOffset) == 68, "slot field offset changed: dataOffset" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->dataOffset) == 4, "slot field size changed: dataOffset" );
static_assert(offsetof(OpenCamBridgeSlotHeader, ringSequence) == 72, "slot field offset changed: ringSequence" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->ringSequence) == 8, "slot field size changed: ringSequence" );
static_assert(offsetof(OpenCamBridgeSlotHeader, streamGeneration) == 80, "slot field offset changed: streamGeneration" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->streamGeneration) == 8, "slot field size changed: streamGeneration" );
static_assert(offsetof(OpenCamBridgeSlotHeader, ringWriteTimestampNs) == 88, "slot field offset changed: ringWriteTimestampNs" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->ringWriteTimestampNs) == 8, "slot field size changed: ringWriteTimestampNs" );
static_assert(offsetof(OpenCamBridgeSlotHeader, sendDeltaUs) == 96, "slot field offset changed: sendDeltaUs" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->sendDeltaUs) == 4, "slot field size changed: sendDeltaUs" );
static_assert(offsetof(OpenCamBridgeSlotHeader, reservedTail) == 100, "slot field offset changed: reservedTail" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->reservedTail) == 4, "slot field size changed: reservedTail" );
static_assert(offsetof(OpenCamBridgeSlotHeader, reserved) == 104, "slot field offset changed: reserved" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->reserved) == 16, "slot field size changed: reserved" );
static_assert(offsetof(OpenCamBridgeSlotHeader, committedEpoch) == 120, "slot field offset changed: committedEpoch" );
static_assert(sizeof(((OpenCamBridgeSlotHeader*)0)->committedEpoch) == 8, "slot field size changed: committedEpoch" );

// What a consumer holding a cursor should read from the history ring. See the Rust
// `ring_select_newest`, which carries the tests for this arithmetic.
struct OpenCamBridgeRingSelection {
    uint64_t ringSequence;
    uint32_t slotIndex;
    // Ring writes between the cursor and this one that this consumer never saw.
    uint64_t skipped;
    // How many of `skipped` the ring had already destroyed.
    uint64_t overwritten;
    // The producer restarted or changed geometry; cursor state is meaningless.
    bool generationChanged;
    // False when this consumer has already seen the frame, so delivering it is a
    // repeat. A caught-up consumer still receives a selection, because Media
    // Foundation must be handed a sample for every request it makes.
    bool fresh;
    bool valid;
};

inline OpenCamBridgeRingSelection OcbSelectNewestRingFrame(
    uint64_t cursorNext, uint64_t cursorGeneration,
    uint64_t writeSequence, uint64_t generation, uint64_t slotCount)
{
    OpenCamBridgeRingSelection selection = {};
    if (slotCount < 2 || writeSequence == 0) return selection;
    selection.valid = true;
    selection.ringSequence = writeSequence;
    selection.slotIndex = static_cast<uint32_t>((writeSequence - 1) % slotCount);
    if (generation != cursorGeneration) {
        selection.generationChanged = true;
        selection.fresh = true;
        return selection;
    }
    selection.fresh = cursorNext <= writeSequence;
    const uint64_t window = slotCount - 2;
    const uint64_t oldestSafe = writeSequence > window ? writeSequence - window : 1;
    selection.skipped = writeSequence > cursorNext ? writeSequence - cursorNext : 0;
    selection.overwritten =
        (selection.fresh && oldestSafe > cursorNext) ? oldestSafe - cursorNext : 0;
    return selection;
}
