// Generated by protocol/generate-ring-abi.ps1. Do not edit.
// Canonical source: protocol/ring-abi.schema.json
pub const RING_ABI_HASH: u64 = 0x9e97cb7c4b267ee7;
pub const RING_ABI_LAYOUT_SHA256: &str = "e77e264b7ccb979e6fd9b44705344d0418019c357335b38c335c68750484e574";
pub const RING_HEADER_SIZE: usize = 320;
pub const SLOT_HEADER_SIZE: usize = 128;
pub const SLOT_COUNT: usize = 8;
const _: () = assert!(std::mem::size_of::<RingHeader>() == RING_HEADER_SIZE);
const _: () = assert!(std::mem::size_of::<SlotHeader>() == SLOT_HEADER_SIZE);
const _: fn(&RingHeader) -> &u32 = |value| &value.magic;
const _: () = assert!(std::mem::offset_of!(RingHeader, magic) == 0);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&RingHeader) -> &u16 = |value| &value.version;
const _: () = assert!(std::mem::offset_of!(RingHeader, version) == 4);
const _: () = assert!(std::mem::size_of::<u16>() == 2);
const _: fn(&RingHeader) -> &u16 = |value| &value.header_size;
const _: () = assert!(std::mem::offset_of!(RingHeader, header_size) == 6);
const _: () = assert!(std::mem::size_of::<u16>() == 2);
const _: fn(&RingHeader) -> &u32 = |value| &value.slot_count;
const _: () = assert!(std::mem::offset_of!(RingHeader, slot_count) == 8);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&RingHeader) -> &u32 = |value| &value.slot_size;
const _: () = assert!(std::mem::offset_of!(RingHeader, slot_size) == 12);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&RingHeader) -> &u32 = |value| &value.max_width;
const _: () = assert!(std::mem::offset_of!(RingHeader, max_width) == 16);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&RingHeader) -> &u32 = |value| &value.max_height;
const _: () = assert!(std::mem::offset_of!(RingHeader, max_height) == 20);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.published_slot;
const _: () = assert!(std::mem::offset_of!(RingHeader, published_slot) == 24);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &u32 = |value| &value.flags;
const _: () = assert!(std::mem::offset_of!(RingHeader, flags) == 28);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.published_sequence;
const _: () = assert!(std::mem::offset_of!(RingHeader, published_sequence) == 32);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.producer_heartbeat_qpc;
const _: () = assert!(std::mem::offset_of!(RingHeader, producer_heartbeat_qpc) == 40);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.consumer_width;
const _: () = assert!(std::mem::offset_of!(RingHeader, consumer_width) == 48);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.consumer_height;
const _: () = assert!(std::mem::offset_of!(RingHeader, consumer_height) == 52);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.consumer_fps_num;
const _: () = assert!(std::mem::offset_of!(RingHeader, consumer_fps_num) == 56);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.consumer_fps_den;
const _: () = assert!(std::mem::offset_of!(RingHeader, consumer_fps_den) == 60);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.virtual_camera_unique_frames;
const _: () = assert!(std::mem::offset_of!(RingHeader, virtual_camera_unique_frames) == 64);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.repeated_virtual_camera_samples;
const _: () = assert!(std::mem::offset_of!(RingHeader, repeated_virtual_camera_samples) == 72);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.consumer_attached;
const _: () = assert!(std::mem::offset_of!(RingHeader, consumer_attached) == 80);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.consumer_pid;
const _: () = assert!(std::mem::offset_of!(RingHeader, consumer_pid) == 84);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.consumer_heartbeat_qpc;
const _: () = assert!(std::mem::offset_of!(RingHeader, consumer_heartbeat_qpc) == 88);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.sample_requests;
const _: () = assert!(std::mem::offset_of!(RingHeader, sample_requests) == 96);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.ring_read_attempts;
const _: () = assert!(std::mem::offset_of!(RingHeader, ring_read_attempts) == 104);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.ring_read_successes;
const _: () = assert!(std::mem::offset_of!(RingHeader, ring_read_successes) == 112);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.ring_validation_failures;
const _: () = assert!(std::mem::offset_of!(RingHeader, ring_validation_failures) == 120);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.sample_copy_failures;
const _: () = assert!(std::mem::offset_of!(RingHeader, sample_copy_failures) == 128);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicI32 = |value| &value.last_ring_error;
const _: () = assert!(std::mem::offset_of!(RingHeader, last_ring_error) == 136);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicI32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.negotiated_subtype;
const _: () = assert!(std::mem::offset_of!(RingHeader, negotiated_subtype) == 140);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.last_accepted_sequence;
const _: () = assert!(std::mem::offset_of!(RingHeader, last_accepted_sequence) == 144);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &u64 = |value| &value.ring_abi_hash;
const _: () = assert!(std::mem::offset_of!(RingHeader, ring_abi_hash) == 152);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&RingHeader) -> &[u8; 32] = |value| &value.installed_dll_build_hash;
const _: () = assert!(std::mem::offset_of!(RingHeader, installed_dll_build_hash) == 160);
const _: () = assert!(std::mem::size_of::<[u8; 32]>() == 32);
const _: fn(&RingHeader) -> &[u8; 32] = |value| &value.producer_build_hash;
const _: () = assert!(std::mem::offset_of!(RingHeader, producer_build_hash) == 192);
const _: () = assert!(std::mem::size_of::<[u8; 32]>() == 32);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.producer_fps_num;
const _: () = assert!(std::mem::offset_of!(RingHeader, producer_fps_num) == 224);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.producer_fps_den;
const _: () = assert!(std::mem::offset_of!(RingHeader, producer_fps_den) == 228);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.resize_backend;
const _: () = assert!(std::mem::offset_of!(RingHeader, resize_backend) == 232);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.resize_failures;
const _: () = assert!(std::mem::offset_of!(RingHeader, resize_failures) == 236);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.ring_write_sequence;
const _: () = assert!(std::mem::offset_of!(RingHeader, ring_write_sequence) == 240);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.stream_generation;
const _: () = assert!(std::mem::offset_of!(RingHeader, stream_generation) == 248);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.ring_frames_overwritten;
const _: () = assert!(std::mem::offset_of!(RingHeader, ring_frames_overwritten) == 256);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.playout_buffer_depth_ns;
const _: () = assert!(std::mem::offset_of!(RingHeader, playout_buffer_depth_ns) == 264);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.playout_target_delay_ns;
const _: () = assert!(std::mem::offset_of!(RingHeader, playout_target_delay_ns) == 272);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.playout_late_dropped;
const _: () = assert!(std::mem::offset_of!(RingHeader, playout_late_dropped) == 280);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.playout_underruns;
const _: () = assert!(std::mem::offset_of!(RingHeader, playout_underruns) == 288);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU64 = |value| &value.playout_scheduler_resets;
const _: () = assert!(std::mem::offset_of!(RingHeader, playout_scheduler_resets) == 296);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU64>() == 8);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicI32 = |value| &value.playout_clock_ppm;
const _: () = assert!(std::mem::offset_of!(RingHeader, playout_clock_ppm) == 304);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicI32>() == 4);
const _: fn(&RingHeader) -> &std::sync::atomic::AtomicU32 = |value| &value.playout_max_output_gap_ms;
const _: () = assert!(std::mem::offset_of!(RingHeader, playout_max_output_gap_ms) == 308);
const _: () = assert!(std::mem::size_of::<std::sync::atomic::AtomicU32>() == 4);
const _: fn(&RingHeader) -> &[u64; 1] = |value| &value.reserved;
const _: () = assert!(std::mem::offset_of!(RingHeader, reserved) == 312);
const _: () = assert!(std::mem::size_of::<[u64; 1]>() == 8);
const _: fn(&SlotHeader) -> &u64 = |value| &value.write_epoch;
const _: () = assert!(std::mem::offset_of!(SlotHeader, write_epoch) == 0);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u64 = |value| &value.sequence;
const _: () = assert!(std::mem::offset_of!(SlotHeader, sequence) == 8);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u64 = |value| &value.capture_timestamp_ns;
const _: () = assert!(std::mem::offset_of!(SlotHeader, capture_timestamp_ns) == 16);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u64 = |value| &value.receive_timestamp_ns;
const _: () = assert!(std::mem::offset_of!(SlotHeader, receive_timestamp_ns) == 24);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u64 = |value| &value.decode_timestamp_ns;
const _: () = assert!(std::mem::offset_of!(SlotHeader, decode_timestamp_ns) == 32);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u32 = |value| &value.width;
const _: () = assert!(std::mem::offset_of!(SlotHeader, width) == 40);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.height;
const _: () = assert!(std::mem::offset_of!(SlotHeader, height) == 44);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.y_stride;
const _: () = assert!(std::mem::offset_of!(SlotHeader, y_stride) == 48);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.uv_stride;
const _: () = assert!(std::mem::offset_of!(SlotHeader, uv_stride) == 52);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.pixel_format;
const _: () = assert!(std::mem::offset_of!(SlotHeader, pixel_format) == 56);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.payload_size;
const _: () = assert!(std::mem::offset_of!(SlotHeader, payload_size) == 60);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.flags;
const _: () = assert!(std::mem::offset_of!(SlotHeader, flags) == 64);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.data_offset;
const _: () = assert!(std::mem::offset_of!(SlotHeader, data_offset) == 68);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u64 = |value| &value.ring_sequence;
const _: () = assert!(std::mem::offset_of!(SlotHeader, ring_sequence) == 72);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u64 = |value| &value.stream_generation;
const _: () = assert!(std::mem::offset_of!(SlotHeader, stream_generation) == 80);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u64 = |value| &value.ring_write_timestamp_ns;
const _: () = assert!(std::mem::offset_of!(SlotHeader, ring_write_timestamp_ns) == 88);
const _: () = assert!(std::mem::size_of::<u64>() == 8);
const _: fn(&SlotHeader) -> &u32 = |value| &value.send_delta_us;
const _: () = assert!(std::mem::offset_of!(SlotHeader, send_delta_us) == 96);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &u32 = |value| &value.reserved_tail;
const _: () = assert!(std::mem::offset_of!(SlotHeader, reserved_tail) == 100);
const _: () = assert!(std::mem::size_of::<u32>() == 4);
const _: fn(&SlotHeader) -> &[u64; 2] = |value| &value.reserved;
const _: () = assert!(std::mem::offset_of!(SlotHeader, reserved) == 104);
const _: () = assert!(std::mem::size_of::<[u64; 2]>() == 16);
const _: fn(&SlotHeader) -> &u64 = |value| &value.committed_epoch;
const _: () = assert!(std::mem::offset_of!(SlotHeader, committed_epoch) == 120);
const _: () = assert!(std::mem::size_of::<u64>() == 8);

/// What a consumer holding a cursor should read from the history ring.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub struct RingSelection {
    /// Ring write sequence to read.
    pub ring_sequence: u64,
    /// Slot holding it.
    pub slot_index: usize,
    /// Ring writes between the cursor and this one that the consumer never saw.
    pub skipped: u64,
    /// How many of `skipped` the ring had already destroyed, so no amount of catching
    /// up could have recovered them. Separates "the ring is too short" from "this
    /// consumer read at the wrong moment".
    pub overwritten: u64,
    /// The producer restarted or changed geometry; cursor state is meaningless, so
    /// losses are reported as zero rather than as an enormous bogus figure.
    pub generation_changed: bool,
    /// False when the consumer has already seen this frame, so delivering it is a
    /// repeat. A caught-up consumer still gets a selection: Media Foundation must be
    /// handed a sample for every request, so "nothing new" has to mean "send the last
    /// one again", never "fail the request".
    pub fresh: bool,
}

/// Pick the newest committed frame and account for what the cursor missed.
///
/// This still selects the NEWEST frame, exactly as the pre-cursor code did, so what
/// the user sees is unchanged. What is new is the accounting, which makes "this
/// consumer skipped two frames" and "this frame was destroyed before anyone read it"
/// separately countable. Reading in cursor order instead of newest-first is a later
/// change, not this one.
#[allow(dead_code)]
pub fn ring_select_newest(
    cursor_next: u64,
    cursor_generation: u64,
    write_sequence: u64,
    generation: u64,
    slot_count: u64,
) -> Option<RingSelection> {
    if slot_count < 2 || write_sequence == 0 {
        return None;
    }
    let slot_index = ((write_sequence - 1) % slot_count) as usize;
    if generation != cursor_generation {
        return Some(RingSelection {
            ring_sequence: write_sequence,
            slot_index,
            skipped: 0,
            overwritten: 0,
            generation_changed: true,
            fresh: true,
        });
    }
    let fresh = cursor_next <= write_sequence;
    let oldest_safe = write_sequence.saturating_sub(slot_count - 2).max(1);
    let skipped = write_sequence.saturating_sub(cursor_next);
    let overwritten = if fresh {
        oldest_safe.saturating_sub(cursor_next)
    } else {
        0
    };
    Some(RingSelection {
        ring_sequence: write_sequence,
        slot_index,
        skipped,
        overwritten,
        generation_changed: false,
        fresh,
    })
}
